# Generated by Django 3.2.7 on 2021-10-25 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Producto', models.CharField(max_length=100)),
                ('Imagen', models.ImageField(upload_to='tienda/static/img/')),
                ('Precio', models.IntegerField()),
                ('Stock', models.IntegerField()),
                ('Descripcion', models.TextField()),
                ('Fecha', models.DateField()),
            ],
        ),
    ]
